config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :prize, presence: true

  PRIZE = %w[watch luxury_dinner weekend_to_hotel].freeze

  def winning_probability
    (1.0 / users_count) * 100
  end

  def users_count
    User.where(prize: prize).size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %w[show]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html {
          redirect_to @user, notice: I18n.t('message', user_count: @user.users_count,
                                                       percentage: @user.winning_probability) 
        }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :prize)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raffle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="card card-body">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label 'Please select your prize' %>
      <%= form.select(:prize, options_for_select(User::PRIZE.map {|k| [k.humanize.capitalize, k]}),{}, class: "form-control") %>
    </div>

    <div class="mt-2">
      <%= form.submit 'Submit', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Users</h1>
  <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
  <div class="card mt-2">
    <table class="table table-bodered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Prize</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.prize %></td>
            <td><%= link_to 'Show', user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class= "container"> 
  <h1 class="text-center">New User</h1>
  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path, class: "mt-2 btn btn-secondary" %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="card mt-5 pl-2">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Selected Prize:</strong>
      <%= @user.prize %>
    </p>

    <%= link_to 'Back', users_path %>
  </div>
</div>